In [2]:
import numpy as np

In [3]:
np.array([ 1,2,3])

array([1, 2, 3])

In [8]:
a= np.array([ 1,2,3])
print(a)

[1 2 3]


In [15]:
b= np.array([1,5,2,3])
print(b)

[1 5 2 3]


In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((2,3,4),dtype= np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [19]:
np.array([])

array([], dtype=float64)

In [23]:
a=np.arange(5 , 10)
print(a)

[5 6 7 8 9]


In [27]:

a = np.matrix('1 2; 3 4')
print("Via string input : \n", a, "\n\n")

Via string input : 
 [[1 2]
 [3 4]] 




In [28]:
np.linspace(0, 100.0, 5)

array([  0.,  25.,  50.,  75., 100.])

In [29]:
np.array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr)

[1 2 3 4 5 6 7 8]


In [38]:
arr1 = np.arange(8).reshape(2, 4)
print("2D arr1 :", arr1)
print("Shape :", arr1.shape)

2D arr1 : [[0 1 2 3]
 [4 5 6 7]]
Shape : (2, 4)


In [39]:
a = np.array([10, 20, 30, 40])
r = np.delete(a, 1)

print(r)

[10 30 40]


In [40]:
arr1 = np.array([1, 2, 3])
print(arr1)

[1 2 3]


In [41]:
arr = np.array([1, 2, 3, 4, 5, 6])
res = np.array_split(arr, 3)
print(res)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [43]:
a = np.array([ 1, 2, 3] )
print ("1st Input array : \n", a)

1st Input array : 
 [1 2 3]


In [44]:
res = np.hstack((a, b))
print(res)

[1 2 3 1 5 2 3]


In [45]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [46]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(np.size(arr))

8


In [47]:
data_type = arr.dtype
print(data_type)

int64


In [48]:

c = np.full([3, 3], 10.1)
print("\nMatrix c : \n", c)


Matrix c : 
 [[10.1 10.1 10.1]
 [10.1 10.1 10.1]
 [10.1 10.1 10.1]]


In [49]:
x = np.random.rand()
print(x)

0.5262581577044984


In [52]:


rng = np.random.default_rng()
numbers = rng.integers(low=0, high=10, size=5)
print(numbers)

[9 8 2 7 4]


In [62]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([7,8,9,10,11,12])

arr1=arr1.reshape(2,-1)
arr2=arr2.reshape(2,-1)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [64]:
sum1=np.sum(arr1,axis=1)
sum2=np.sum(arr2,axis=1)
print(sum1)
print(sum2)

[ 6 15]
[24 33]


In [65]:
mean1=np.mean(arr1,axis=0)
mean2=np.mean(arr2,axis=0)
print("mean of arr1",mean1)
print("mean of arr2",mean2)

mean of arr1 [2.5 3.5 4.5]
mean of arr2 [ 8.5  9.5 10.5]


In [63]:
np.ndim(arr1)

2

In [67]:
rng = np.random.default_rng()
numbers = rng.integers(low=0, high=10, size=6)
print(numbers)

[4 0 0 3 5 1]


In [69]:
numbers.reshape(2,-1)

array([[4, 0, 0],
       [3, 5, 1]])

In [72]:
rng=np.random.default_rng()
a1=rng.random(6)
a2=rng.random(6)
print(a1)
print(a2)

[0.34013279 0.4509902  0.94443054 0.33152101 0.43131865 0.01254699]
[0.62633893 0.83598529 0.84483765 0.44410737 0.76744187 0.30727278]


In [73]:
np.hstack((a1,a2))

array([0.34013279, 0.4509902 , 0.94443054, 0.33152101, 0.43131865,
       0.01254699, 0.62633893, 0.83598529, 0.84483765, 0.44410737,
       0.76744187, 0.30727278])

In [74]:
np.vstack((a1,a2))

array([[0.34013279, 0.4509902 , 0.94443054, 0.33152101, 0.43131865,
        0.01254699],
       [0.62633893, 0.83598529, 0.84483765, 0.44410737, 0.76744187,
        0.30727278]])

In [76]:
ones=np.ones(3)
print(ones)

[1. 1. 1.]


In [77]:
unit=np.eye(4)
print(unit)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [79]:

import numpy as np

# Creating matrices using the newer Generator API
rng = np.random.default_rng()
A = rng.integers(1, 10, size=(3, 3))
B = rng.integers(1, 10, size=(3, 3))

# 1. Addition using the explicit function
# This is equivalent to A + B
matrix_sum = np.add(A, B)

# 2. Multiplication (Dot Product) using np.dot
# This is equivalent to A @ B
matrix_product = np.dot(A, B)

# 3. BONUS: Element-wise Multiplication
# This multiplies corresponding positions only
element_prod = np.multiply(A, B)

In [80]:
matrix_sum

array([[16,  9,  7],
       [ 4,  9, 12],
       [ 8, 10, 14]])

In [82]:
matrix_product

array([[ 91,  39, 101],
       [ 42,  64,  96],
       [ 63,  54,  93]])

In [84]:
element_prod

array([[63,  8, 10],
       [ 3, 14, 35],
       [12, 21, 48]])