In [ ]:
import numpy as np

In [ ]:
np.array([ 1,2,3])

array([1, 2, 3])

In [ ]:
a= np.array([ 1,2,3])
print(a)

[1 2 3]


In [ ]:
b= np.array([1,5,2,3])
print(b)

[1 5 2 3]


In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2,3,4),dtype= np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
np.array([])

array([], dtype=float64)

In [ ]:
a=np.arange(5 , 10)
print(a)

[5 6 7 8 9]


In [ ]:

a = np.matrix('1 2; 3 4')
print("Via string input : \n", a, "\n\n")

Via string input : 
 [[1 2]
 [3 4]] 




In [ ]:
np.linspace(0, 100.0, 5)

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
np.array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr)

[1 2 3 4 5 6 7 8]


In [ ]:
arr1 = np.arange(8).reshape(2, 4)
print("2D arr1 :", arr1)
print("Shape :", arr1.shape)

2D arr1 : [[0 1 2 3]
 [4 5 6 7]]
Shape : (2, 4)


In [ ]:
a = np.array([10, 20, 30, 40])
r = np.delete(a, 1)

print(r)

[10 30 40]


In [ ]:
arr1 = np.array([1, 2, 3])
print(arr1)

[1 2 3]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
res = np.array_split(arr, 3)
print(res)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
a = np.array([ 1, 2, 3] )
print ("1st Input array : \n", a)

1st Input array : 
 [1 2 3]


In [ ]:
res = np.hstack((a, b))
print(res)

[1 2 3 1 5 2 3]


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(np.size(arr))

8


In [ ]:
data_type = arr.dtype
print(data_type)

int64


In [ ]:

c = np.full([3, 3], 10.1)
print("\nMatrix c : \n", c)


Matrix c : 
 [[10.1 10.1 10.1]
 [10.1 10.1 10.1]
 [10.1 10.1 10.1]]


In [ ]:
x = np.random.rand()
print(x)

0.014895662039346669


In [ ]:


rng = np.random.default_rng()
numbers = rng.integers(low=0, high=10, size=5)
print(numbers)

[3 6 5 9 4]


In [ ]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([7,8,9,10,11,12])

arr1=arr1.reshape(2,-1)
arr2=arr2.reshape(2,-1)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
sum1=np.sum(arr1,axis=1)
sum2=np.sum(arr2,axis=1)
print(sum1)
print(sum2)

[ 6 15]
[24 33]


In [ ]:
mean1=np.mean(arr1,axis=0)
mean2=np.mean(arr2,axis=0)
print("mean of arr1",mean1)
print("mean of arr2",mean2)

mean of arr1 [2.5 3.5 4.5]
mean of arr2 [ 8.5  9.5 10.5]


In [ ]:
np.ndim(arr1)

2

In [ ]:
rng = np.random.default_rng()
numbers = rng.integers(low=0, high=10, size=6)
print(numbers)

[0 3 7 9 6 6]


In [ ]:
numbers.reshape(2,-1)

array([[0, 3, 7],
       [9, 6, 6]])

In [ ]:
rng=np.random.default_rng()
a1=rng.random(6)
a2=rng.random(6)
print(a1)
print(a2)

[0.67605201 0.08600612 0.85044079 0.1458405  0.61186283 0.01568201]
[0.61228772 0.55368644 0.31727194 0.62100457 0.66635459 0.19196974]


In [ ]:
np.hstack((a1,a2))

array([0.67605201, 0.08600612, 0.85044079, 0.1458405 , 0.61186283,
       0.01568201, 0.61228772, 0.55368644, 0.31727194, 0.62100457,
       0.66635459, 0.19196974])

In [ ]:
np.vstack((a1,a2))

array([[0.67605201, 0.08600612, 0.85044079, 0.1458405 , 0.61186283,
        0.01568201],
       [0.61228772, 0.55368644, 0.31727194, 0.62100457, 0.66635459,
        0.19196974]])

In [ ]:
ones=np.ones(3)
print(ones)

[1. 1. 1.]


In [ ]:
unit=np.eye(4)
print(unit)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:

import numpy as np

# Creating matrices using the newer Generator API
rng = np.random.default_rng()
A = rng.integers(1, 10, size=(3, 3))
B = rng.integers(1, 10, size=(3, 3))

# 1. Addition using the explicit function
# This is equivalent to A + B
matrix_sum = np.add(A, B)

# 2. Multiplication (Dot Product) using np.dot
# This is equivalent to A @ B
matrix_product = np.dot(A, B)

# 3. BONUS: Element-wise Multiplication
# This multiplies corresponding positions only
element_prod = np.multiply(A, B)

In [ ]:
matrix_sum

array([[ 4, 10, 14],
       [ 8,  7,  4],
       [ 2, 12,  4]])

In [ ]:
matrix_product

array([[16, 83, 45],
       [21, 63, 65],
       [ 6, 20, 16]])

In [ ]:
element_prod

array([[ 4, 25, 49],
       [ 7, 10,  4],
       [ 1, 27,  3]])

In [ ]:
rng=np.random.default_rng()
a1=rng.random(6)
a2=rng.random(6)
print(a1)
print(a2)

[0.60401108 0.59199878 0.35606228 0.08423021 0.54013203 0.51929523]
[0.4221134  0.63543199 0.89148324 0.46186846 0.21730585 0.70334841]


In [ ]:
merged=np.concatenate((a1,a2))
print(merged)

[0.60401108 0.59199878 0.35606228 0.08423021 0.54013203 0.51929523
 0.4221134  0.63543199 0.89148324 0.46186846 0.21730585 0.70334841]


In [ ]:
Min max
Mean median mode
copy fun
View fun
Array indexing slicing
Condition search

In [ ]:
# finding the maximum and
# minimum element in the array
max_element = np.max(arr)
min_element = np.min(arr)

# printing the result
print('maximum element in the array is: ',
      max_element)
print('minimum element in the array is: ',
      min_element)

maximum element in the array is:  8
minimum element in the array is:  1


In [ ]:

arr = np.array([2, 4, 6, 8, 10])
c = arr.copy()

print("Original ID:", id(arr))
print("Copy ID:    ", id(c))

Original ID: 134432976213008
Copy ID:     134432986326448


In [ ]:
speed = [99,86,87,88,111,86,103,87,94,78,77,85,86]

x = np.mean(speed)

print(x)

89.76923076923077


In [ ]:
a = np.arange(10, dtype ='int16')
print("a is: \n", a)

a is: 
 [0 1 2 3 4 5 6 7 8 9]


In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix[1, 2])

6


In [ ]:
import numpy as np

arr1 = np.arange(10, 1, -2)
print("Array:", arr1)

arr2 = arr1[[3, 1, 2]]
print("Elements at specified indices:", arr2)

Array: [10  8  6  4  2]
Elements at specified indices: [4 8 6]


In [ ]:
# importing the module
import numpy as np

# creating the array
arr = np.array([10, 32, 30, 50, 20, 82, 91, 45])

#  printing arr
print("arr = {}".format(arr))

#  looking for value 30 in arr and storing its index in i
i = np.where(arr == 30)
print("i = {}".format(i))

arr = [10 32 30 50 20 82 91 45]
i = (array([2]),)


In [ ]:
What is pandas function in numpy
What are use it ?

In [ ]:
import pandas as pd
df = pd.DataFrame()

df['Name'] = ['John', 'Emma', 'Liam', 'Olivia']
df['Age'] = [20, 19, 21, 18]
df['Student'] = [True, True, False, True]

print(df)

     Name  Age  Student
0    John   20     True
1    Emma   19     True
2    Liam   21    False
3  Olivia   18     True


In [ ]:
import pandas as pd

df = pd.DataFrame({ 'Date': ['10/2/2011', '11/2/2011', '12/2/2011', '13/2/2011'],
                    'Product': ['Umbrella', 'Mattress', 'Badminton', 'Shuttle'],
                    'Last Price': [1200, 1500, 1600, 352],
                    'Updated Price': [1250, 1450, 1550, 400],
                    'Discount': [10, 10, 10, 10] })
print(df)

        Date    Product  Last Price  Updated Price  Discount
0  10/2/2011   Umbrella        1200           1250        10
1  11/2/2011   Mattress        1500           1450        10
2  12/2/2011  Badminton        1600           1550        10
3  13/2/2011    Shuttle         352            400        10


In [ ]:
import pandas as pd
df = pd.DataFrame({'A': [10, 20], 'B': [30, 40], 'C': [50, 60]})
df.rename(columns={'A': 'X', 'B': 'Y'}, inplace=True)
print(df)

    X   Y   C
0  10  30  50
1  20  40  60


In [ ]:
import pandas as pd

df = {
  "Array_1": [49.50, 70],
  "Array_2": [65.1, 49.50]
}

data = pd.DataFrame(df)

print(data.replace(49.50, 60))

   Array_1  Array_2
0     60.0     65.1
1     70.0     60.0


In [ ]:
import pandas as pd
import numpy as np

# 1. Create a sample DataFrame
data = {
    'Full_Name': ['ALICE smith', 'bob JOHNSON', 'charlie BROWN', 'DANA white'],
    'Age': [25, 17, 30, 15],
    'City': ['New York', 'London', 'new york', 'Paris'],
    'Score': [88, 42, 95, 60]
}

df = pd.DataFrame(data)
print("--- Original DataFrame ---")
print(df)

# 2. Rename columns (Lowercase the headers)
df = df.rename(columns={'Full_Name': 'name', 'Age': 'age', 'City': 'city', 'Score': 'score'})

# 3. Case Conversion (Normalize the 'name' column)
df['name'] = df['name'].str.title()

# 4. Replace values (Fixing inconsistent city names)
df['city'] = df['city'].replace('new york', 'New York')

# 5. Condition Function (Assign 'Status' based on age)
df['status'] = np.where(df['age'] >= 18, 'Adult', 'Minor')

# 6. Sorting (Shorts - Sort by score descending)
df = df.sort_values(by='score', ascending=False)

print("\n--- Processed DataFrame ---")
print(df)

--- Original DataFrame ---
       Full_Name  Age      City  Score
0    ALICE smith   25  New York     88
1    bob JOHNSON   17    London     42
2  charlie BROWN   30  new york     95
3     DANA white   15     Paris     60

--- Processed DataFrame ---
            name  age      city  score status
2  Charlie Brown   30  New York     95  Adult
0    Alice Smith   25  New York     88  Adult
3     Dana White   15     Paris     60  Minor
1    Bob Johnson   17    London     42  Minor
